<?php

namespace ApiBundle\Repository;

/**
 * ClaimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClaimRepository extends \Doctrine\ORM\EntityRepository
{
}
